sudo: required
notifications:
  email: false
services:
  - docker
script:
  - export IMAGE_NAME=romischart/node-chrome
  - docker build -t $IMAGE_NAME .
  - export CHROME_VERSION=$(docker run --entrypoint "google-chrome" $IMAGE_NAME -version | awk '{ print $3 }')
after_success:
  - docker login -u=$DOCKER_USER -p=$DOCKER_PASS
  - docker tag $IMAGE_NAME $IMAGE_NAME:$CHROME_VERSION
  - docker push $IMAGE_NAME